logging:
  level:
    org.hibernate.SQL: debug

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
        # ddl-auto: 'option'
          # none : ???? ?? ???.
          # create : ??? ???? ???, ??? ?? ??.
          # create-drop : ???? ?? ???, ?? ??? ?? ???.
          # update : Entity?? ??? ??? ???? ????.(??? ??)
          # validate : Entity? ???? ???? ??? ????.(???? ??? ?? : Application ??)
      properties:
        hibernate:
          #show_sql: true
            # System.out? ?????? ?? SQL? ??
          format_sql: true
          use_sql_comments: true
            # ??? ???? ??? ?? ?? ??? ???? HINT? ??

        # default_batch_fetch_size: 500 # in (, , , ,) ? ??, 100 ~ 1000

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    path: /swagger.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**